#data driven config path
project_path: .
data_path: "test_data.csv" # path to validation data (within project folder)
model_path: "models/sequifier-default-best-300.onnx" # path to model (within project folder)
device: "cpu" # device used for inference
seq_length: 10 # sequence length for prediction (must be identical to training)
output_probabilities: True # write out class probablities for further processing
map_to_id: False # map predictions from indices to labels (requires ddconfig_path)

inference_batch_size: 10
log_interval: 100

categorical_columns: ["itemId"]
real_columns: []
target_column: "itemId"
target_column_type: "categorical"
n_classes: {
  "itemId": 10
}
column_types:  {
  "itemId": "int64"
}

read_format: csv
autoregression: false